### PR TITLE
Publish to Artifactory on release

### PR DESCRIPTION
**Pull request by alansemenov**

### CODE REVIEW

**Review by rymsha — CHANGES_REQUESTED** [review]
something is wrong here. we build our libs with simplified workflow
https://github.com/enonic/lib-cache/blob/master/.github/workflows/enonic-gradle.yml

**Comment by alansemenov** [comment]
> something is wrong here. we build our libs with simplified workflow https://github.com/enonic/lib-cache/blob/master/.github/workflows/enonic-gradle.yml

We need to publish on NPM with every release. Do we need two separate actions for release?

**Review by ComLock — APPROVED** [review]

**Comment by rymsha** [comment]
we could improve simplified workflow to do that @alansemenov

**Comment by alansemenov** [comment]
> we could improve simplified workflow to do that @alansemenov

Then we need to rename the workflow file, otherwise it will be overwritten on the next batch update of the standard workflow

**Comment by rymsha** [comment]
> next batch update

we don't do it anymore

**Pull request merged**
